package com.leapsy.personalizesettingkotlin.recyclerAdapterViewHolders.mainPage

import androidx.recyclerview.widget.RecyclerView
import com.leapsy.personalizesettingkotlin.databinding.MemberPersonalizeSettingItemBinding

class CustomMenuThemeViewHolder(val mainPersonalizePageBinding : MemberPersonalizeSettingItemBinding) : RecyclerView.ViewHolder(mainPersonalizePageBinding.root) {
}